### ISSUE TITLE
DecryptException : The payload is invalid

### ISSUE THREAD

**Issue by maxsprite** [calebporzio/livewire#113]
Hello. Package look pretty good, but I have error after start using this. Wherein main functional of package - work fine.

**Describe the bug**

In clear laravel 5.8 setup and after finish `composer require calebporzio/livewire` command, i got error in console after running `php artisan route:list` command. 

Error message:  **Illuminate\Contracts\Encryption\DecryptException  : The payload is invalid.**

**To Reproduce**

1. Open Terminal on Linux based OS (in my case - Mac OS)
2. Run command `laravel new awesome-project`
3. Run command `cd awesome-project`
4. Run command `composer require calebporzio/livewire`
5. Run command `php artisan route:list`
6. See error

**Screenshots**

[https://www.dropbox.com/s/sc7mqhnwjkboe33/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202019-08-03%20%D0%B2%2018.58.06.png?dl=0](url)

**Comment by maxsprite** [comment]
Guys, i found **HttpConnectionHandler** class (vendor/calebporzio/livewire/src/Connection/HttpConnectionHandler.php), where we get value from **decrypt** in **getMiddleware** function. But if we **decrypt** NULL value - get **DecryptException**. In this case i think we need `if (request('middleware') !== null)` or `try {} case () {}` construction. 

In my local solution i rewrite source code like this:

```
    // This simulates extending Illuminate/Routeing/Controller
    public function getMiddleware()
    {
        $middleware = [];
        if (request('middleware') !== null) {
            $middleware = decrypt(request('middleware'), $unserialize = true);
        }

        return array_map(function ($m) {
            return [
                'middleware' => $m,
                'options' => [],
            ];
        }, $middleware);
    }
```

After this `php artisan route:list` command work fine.

**Comment by calebporzio** [comment]
Good catch @maxsprite, and thanks for providing a solution.

However, I think that solution creates a vulnerability in the framework.

I have created my own fixed and pushed it to master. It will be available in the latest release when I tag it. Thanks.
