### ISSUE TITLE
Deep nested data validated wrong - nested rule values overwrite root rule values

### ISSUE THREAD

**Issue by faustbrian** [calebporzio/livewire#120]
Livewire at the moment seems to handle deep nested data and validation in a wrong way. The given example results in such wrong way of handling it.

```php
// View
<input type="text" wire:model="items.{{ $loop->index }}.api_key" />
<input type="text" wire:model="items.{{ $loop->index }}.api_secret" />
<input type="text" wire:model="items.{{ $loop->index }}.from" />
<input type="text" wire:model="items.{{ $loop->index }}.to" />

// Component
public function persist(): void
{
    $data = this->validate([
        'items'              => ['required', 'array'],
        'items.*'            => ['array'],
        'items.*.api_key'    => ['required', 'string'],
        'items.*.api_secret' => ['required', 'string'],
        'items.*.from'       => ['required', 'numeric'],
        'items.*.to'         => ['required', 'numeric'],
    ]);
    
    $this->getModel()->settings()->set('notifications.nexmo', $data['items']);
}
```

[This line](https://github.com/calebporzio/livewire/blob/master/src/Concerns/ValidatesInput.php#L22) changes the `items` property from being an associative array with nested items to simply become `'items' => 'items.*.to'`.

I tested this with various different nested rules and it seems to always overwrite the root rule with the last nested rule. What I mean by this is that `items` is the root rule and `items.*.to` is the last nested rule and that last nested rule overwrites `items` with its value.

**Comment by calebporzio** [comment]
You're right, that line was clobbering the validation input.

I fixed this, and the fix will be available in the next release.
