### ISSUE TITLE
Collision with component name property for render method view

### ISSUE THREAD

**Issue by faustbrian** [calebporzio/livewire#130]
https://github.com/calebporzio/livewire/commit/8d0137fa7919a6b4b3babf6245c044fcb524046e#diff-c694a29ec41709ca1a5f5e8a29f6467eR45

This line performs a check to either use the `$this->name` property or build a name from the class name. This results in a collision with components that have a property called `name` like contact forms or user editing forms.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class UpdateContactInformation extends Component
{
    /** @var string */
    public $name;
}
```

With this code you can start typing in a name in an input and an error modal will pop up that will tell you something to the effect of `View [value of $name] doesn't exist`.

My first idea for a solution would be to create a method like `getName()` that developers can use to apply a custom name to their component instead of relying on a base `$name` property which will commonly be overwritten by various components.

**Comment by calebporzio** [comment]
I think that's a great solution - is this something that you could PR?

**Comment by faustbrian** [comment]
Done in https://github.com/calebporzio/livewire/pull/131
