### ISSUE TITLE
Pass data to updating/updated methods

### ISSUE THREAD

**Issue by marksalmon** [calebporzio/livewire#134]
**Is your feature request related to a problem? Please describe.**
Less a problem than an inconvenience. With components that contain a lot of properties you can end up writing many identical/similar ```updatedFoo``` methods.

**Describe the solution you'd like**
I would like the generic ```updated``` / ```updating``` methods in a livewire component to receive data, so that logic can be performed conditionally depending on the name or value of the updated property

**Describe alternatives you've considered**
The ```updatingFoo``` and ```updatedFoo``` methods already receive ```$value``` so you can work round this just by writing a specific method for each property

**Additional context**
* Example (pseudo-code)

```php
public function updated($data)
{
    // ... do some validation.

    $this->model()->persistToDatabase($data['name'], $data['value']);
}
```

**Comment by calebporzio** [comment]
This has been merged and added to the framework (will be in the next release):

```
public function updated($name, $value)
{
    // ... do some validation.

    $this->model()->persistToDatabase($name, $value);
}
```
