### ISSUE TITLE
Trigger an action on load

### ISSUE THREAD

**Issue by marin246** [calebporzio/livewire#136]
I can't find a simple way to have livewire trigger an action on page load/ready. This is often very handy to ensure quick pageload times: display all "fast" content on first request, then display "slow" content via livewire after it is e.g. fetched from some third-party API.

**Describe the solution you'd like**
```
<div wire:load="fetchSlowContent">
{{ $mySlowContent }}
</div>
```
Is there any technical limitation, which prohibits doing this?

**Describe alternatives you've considered**
Have some button, that fetches/refreshes the slow content and trigger it automatically on pageload.
```
function click() {
   document.getElementById("fetcher").click()
}
document.addEventListener("DOMContentLoaded", click);
```
However, this is clearly not as elegant

**Comment by calebporzio** [comment]
Good call, I've thought about this too. Added `wire:init` on latest release (v0.1.6)

**Comment by marin246** [comment]
Awesome!
