### ISSUE TITLE
Redirect helpers for routes and actions on component

### ISSUE THREAD

**Issue by faustbrian** [calebporzio/livewire#140]
It would be nice to have helpers for route and action redirects directly on the component instead of having to call the `route` or `action` helpers and pass them to the `redirect` method.

```php
// Before
$this->redirect(route('dashboard.projects.edit', $project));

// After
$this->redirectToRoute('dashboard.projects.edit', $project);
```

See https://github.com/faustbrian/livewire/commit/2bf40e57db3ccffd72c6c365f1d86a7896877448

**Comment by calebporzio** [comment]
Yeah, I'm game. I'd probably rather: `redirectRoute()` though
