### ISSUE TITLE
Easy way of keeping model instance alive?

### ISSUE THREAD

**Issue by faustbrian** [calebporzio/livewire#143]
https://github.com/calebporzio/livewire/commit/102f0879003afd095790bbc4313b6b8bfda96de0

Recently a breaking changed was introduced for when the `updating` and `updated` events are called which broke an application I am working on. I used the way those lifecycle events were called to keep the models in my component updated to be instances instead of arrays.

What would be the recommended way now to keep a model instance inside the component after the change to those events? It's rather tedious to have multiple manual `Model::findOrFail($this->model['id'])` calls inside a component so the previous method with lifecycle events was an easy and cheap _(with model caching)_ way of keeping the model instance alive.

**This code no longer works because `updating` is never called in time.**
```php
<?php

namespace App\Http\Livewire\Concerns;

use App\Models\Organisation;

trait BelongsToOrganisation
{
    /** @var Organisation */
    public $organisation;

    /**
     * Mount the component.
     */
    public function mount(Organisation $organisation): void
    {
        $this->organisation = $organisation;
    }

    /**
     * Handle the "updating" lifecycle hook.
     */
    public function updating(): void
    {
        $this->organisation = Organisation::findOrFail($this->organisation['id']);
    }
}
```

**Comment by calebporzio** [comment]
Wondering if we create different lifecycle hooks.

Like `->hydrating` and `->dehydrating` (these would behave like the old updated/updating)

What do you think?

**Comment by calebporzio** [comment]
Ok, I added a new lifecycle hook called `->hydrate()` that will be like a "mount()", except it will run at the beginning of every Livewire request. (but not the first load -> that's where mount() will run).

It will be available in the next release.

**Comment by faustbrian** [comment]
Thanks, that got me up and running again. Will be useful for a lot of people to maintain their model state.
