### ISSUE TITLE
Best Practice Question

### ISSUE THREAD

**Issue by evergreenwebsystems** [calebporzio/livewire#144]
I am newish to Laravel so was just looking for some advice really on best practice in terms of using Livewire within Laravel.

It is obviously possible to validate and persist data to the database directly in a Livewire component, for example:

```
 public function createProject()
 {
        $attributes = $this->validate([
            'title' => 'required|min:1',
            'description' => 'required|min:1',
        ]);
        $project = Project::create($attributes);
        $project->users()->attach(auth()->user());

        $this->emit('renderProjects');
        $this->emit('closeModal');
}
```
However, it is my understanding that there is a certain philosophy in the Laravel community which says you should keep things clean and organised and, for example, only use the standard index, show, create, store, edit, update and destroy methods in a Controller. Don't use your own named methods in a controller, just the before mentioned ones. If your using a Livewire component like a Controller then this is no longer possible, i.e the very nature of Livewire means you will of course have other functions within the component.

So, should I keep my index, show, create, store, edit, update and destroy methods out of my Livewire components and instead use an internal API kind of setup whereby I send internal requests to the controllers, for example the above function could be re-written like this:

```
 public function createProject()
 {
        $attributes = $this->validate([
            'title' => 'required|min:1',
            'description' => 'required|min:1',
        ]);

        $request = Request::create('api/projects', 'POST', $attributes);
        app()->handle($request);

        $this->emit('renderProjects');
        $this->emit('closeModal');
}
```
I know these things are probably a matter of personal preference. However, my second suggestion might be a daft idea for all I know! So, I am interested in some opinions of more experienced Laravel developers.

Thanks!

**Comment by calebporzio** [comment]
Yeah, it's a good question.

I think you can still have "RESTfull" methods in a Livewire component. But I personally wouldn't stick to it as strictly, because you would be forced to break things out into multiple components which isn't as cheap as breaking things out into separate controllers.

I personally would be fine doing validation and model creation inside a Livewire component method. I imagine some conventions will emerge, but for now, I'd say don't worry about it.

**Comment by evergreenwebsystems** [comment]
Thanks for the reply.

As a brief follow up am I right in saying you would never or call a method in a Controller directly from a Livewire Component? I.e is this would be bad practice.

Also, would you consider putting the model creation/update/destroy in the model itself?

**Comment by calebporzio** [comment]
A. Yes, I would avoid calling controller methods from inside component
B. Yes, I would put creation logic in the model if it was complex (but I would name it something other than just overriding "create")

**Comment by evergreenwebsystems** [comment]
Okay. I will stick with keeping the validation and creation inside the Livewire component at the moment. However, I am interested to see what develops as best practice.

For example, to my inexperienced eye this would appear to work quite well.

LIvewire component:
```
    public function createProject()
    {
        (new ProjectsController)->store($this);

        $this->emit('renderProjects');
        $this->emit('closeModal');
    }
```

Standard Laravel API controller:
```
    public function store($request)
    {
        $project = Project::create($request->validate([
            'title' => ['required', 'min:3'],
            'description' => ['required', 'min:3']
        ]));
        $project->users()->attach(auth()->user());
    }
```

I.e. this keeps the Restful behaviour within a standard API Controller and leaves the Livewire component to deal just with the reactivity element. Similar to how you pass data from a Vue component to a Controller.

Thanks for the advice.

**Comment by calebporzio** [comment]
Wow, that's kind of crazy that the `$this` behaves as a substitute for the `$request`. Feels risky,  but definitely pretty cool

**Comment by evergreenwebsystems** [comment]
Apologies for coming back to this again. I understand why I would not call a Controller from a Controller, there is plenty of stuff online about why this is bad practice.

However, I think I am right in saying that a Livewire component is not a Controller? It essentially replaces, for example, Vue. My understanding is that Vue is kind of a bridge between a Controller and a View, and in this case Livewire is performing a similar role? 

You do use Vue to interact with a Controller, i.e. via Axios and API routes, so given that premise could it be considered okay to access a Controller from a Livewire component?

If I want my Laravel app to be consumed by a website plus some mobile apps via an API then in order to keep things dry I should be using API controllers shouldn't I?

With respect to the risky ```$this``` substitution what about if it is actually put into a normal request, like this:

```
(new ProjectsController)->store(new Request(collect($this)->toArray()));
```

Isn't that performing a similar function to something you might have in Vue like this:

```
        createPost({commit}, post) {
            axios.post('/api/posts', post)
                .then(res => {
                    commit('CREATE_POST', res.data)
                }).catch(err => {
                console.log(err)
            })
        },
```

**Comment by davidpiesse** [comment]
I think it is fair to consider the PHP side of a Livewire Component at least partially a Controller.
You have access to redirect(), validation and other methods that are more controller than anything else.

With Vue - it does front-end manipulation (as does LW), it persists data between actions (as does LW), but Vue does not store data in a DB (LW does - Vue calls a endpoint).
Vue is def not a Controller in these circumstances - it just interacts with one.

Livewire can effectively / is capable of more in it's scope than Vue but I would recommend that the logic is separated.

Hopefully that is helpful... it's a bit of a thinking point 😺

**Comment by evergreenwebsystems** [comment]
I agree, Livewire is capable of far more than Vue. Equally, your description of a Livewire Component being considered partially a Controller I agree with, but don't you think that makes things abit fuzzy then in terms of where to actually put logic that would normally live in a Controller?

You say "I would recommend that the logic is separated.", so where would you put it. In a Model?
I.e. As per my earlier example would you put the logic for a more complicated store method if you want it to be accessible via an API endpoint as well as via Livewire directly in a Model? 

You guys know a ton more about this than I do, so I am sure if it was worthwhile you would have considered it already but is there any merit in a creating a 'safe' way in a Livewire component to directly interact with a Controller? For all I know its not really possible or just plain abad idea, I am just asking because I don't know?

I hope your not finding my questions too annoying! I am really interested because I think Livewire is incredible and I as I am sure I will be using it in every project I really want to try and implement it in the best possible way.

**Comment by ballerburg9005** [comment]
Yeah, this is very important to know. Why is this even closed?

The issue really is, that you can use Livewire to replace single Blade views, or all views, one controller all controllers, then you can run them in parallel or in chains and you can also use it to partially replace things.

I don't see how the docs really cover this, but it surely makes some difference somewhere other than code hygiene.

**Comment by ballerburg9005** [comment]
I mean, check this out. I am a noob and I just wrote this:

[Ideas.php.txt](https://github.com/livewire/livewire/files/5340867/Ideas.php.txt)

[livewire-wrapper.blade.php.txt](https://github.com/livewire/livewire/files/5340869/livewire-wrapper.blade.php.txt)

I made the component the resource controller and call Livewire through a wrapper, so I can use my components for the standard CRUD requests in single page views, or as widgets, without creating thousands of additional duplicate files.

Why not?

Is that bad?

You would believe that this is the very first thing people will be intuitively doing, because it makes things so much easier.

**Comment by ballerburg9005** [comment]
Ok, please don't do what I did. It will totally blast half of your database into the JS frontend, expose user emails and god knows what. Its almost like combining the disadvantages of Vue, with the disadvantages of Livewire.

It would be nice if there were guidelines and working examples to cover this kind of stuff.

**Comment by vahidalvandi** [comment]
Please expand this topic as our app needs to connect to the api
