### ISSUE TITLE
Using a subdomain does not work

### ISSUE THREAD

**Issue by intellow** [calebporzio/livewire#155]
If you try to use livewire from a subdomain (like if you have a multi-tenant app), you get this error in the browser console.

Access to fetch at 'https://domain.test/livewire/message' from origin 'https://sub.domain.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ceejayoz** [comment]
Do you have `app.url` explicitly set to `domain.test`?

**Comment by intellow** [comment]
> Do you have `config('app.url')` explicitly set to `domain.test`?

Yes, my .env has `APP_URL=https://domain.test`. I tried updating my .env to `APP_URL=https://*.domain.test` and when I did that Livewire did not work at all. Does Laravel support that type of setting for multi-tenant apps? If so, I'm not aware.

**Comment by edgrosvenor** [comment]
I've used this package to simplify CORS management before and it's pretty straightforward. It might be the key to your happiness.

https://github.com/barryvdh/laravel-cors

**Comment by intellow** [comment]
@edgrosvenor I tried to install that package and add HandleCors to the global middleware. It doesn't work but it does change the error:

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at livewire.js?id=e21774621afc85fe1711:1
```

**Comment by calebporzio** [comment]
@intellow, This is usually caused by something weird coming back from a Livewire ajax request. Something non-standard. Can you inspect the XHR requests and post the raw output from the one at fault?

**Comment by intellow** [comment]
@calebporzio Thanks for the tip. It didn't solve the problem, but the response is the full HTML of my login page. I imagine somewhere along the line there was some return of a redirect to the login page. I thought it might be some custom middleware I've written but I disabled all my custom middleware and it's still happening. Again, if I remove the subdomain from the URL (in which case my app still works), Livewire works fine.

**Comment by edgrosvenor** [comment]
@intellow That explains your problem then. The expected response is JSON, not HTML. If you fully trust the server you're requesting from you can use JSONP which would allow you to receive the HTML page back instead of JSON. https://www.w3schools.com/js/js_json_jsonp.asp

**Comment by edgrosvenor** [comment]
Oh... but if it's a Livewire ajax request that's receiving it, you probably can't do that.

**Comment by intellow** [comment]
> @intellow That explains your problem then. The expected response is JSON, not HTML. If you fully trust the server you're requesting from you can use JSONP which would allow you to receive the HTML page back instead of JSON. https://www.w3schools.com/js/js_json_jsonp.asp

I can't figure out why livewire is returning the login page url

**Comment by edgrosvenor** [comment]
@intellow  I've solved your problem. The CORS thing should have been a red flag for me. Livewire uses the APP_URL value from your .env file to build the URL for its requests. 

On my local machine, I was able to duplicate your problem like this:

APP_URL=http://college_portal.test

Load a page with the component at http://whatever.college_portal.test

And I fixed it by changing my .env file to:

APP_URL=http://whatever.college_portal.test

@calebporzio This probably needs to be mentioned in the docs unless you want to remove the use of that environment variable and just hit a relative URL from wherever the component happens to live.

**Comment by intellow** [comment]
@edgrosvenor thanks, but unfortunately that doesn't solve my problem. I have potentially unlimited sub domains for my app. Each new customer (tenant) chooses their subdomain. It would be great if we could change the livewire setting to allow *.domain.com or even define the list of acceptable subdomains.

**Comment by edgrosvenor** [comment]
@intellow As an alternative, unless your app uses the 
APP_URL value for something else, just remove it from your .env file. It'll solve this problem and might not introduce new ones. I'm not sure, but I think Laravel's behavior is to just use relative urls if that value is missing or set to localhost.

**Comment by edgrosvenor** [comment]
Actually don't do that if you run jobs or commands that might need to know the URL of your app. If you delete that value or change it to localhost, jobs and commands will try to use that.

**Comment by intellow** [comment]
Yeah, I definitely use that value. I'll keep trying to think of another solution.

**Comment by edgrosvenor** [comment]
@intellow Here's where it all went wrong for you: https://github.com/calebporzio/livewire/pull/89

Basically what @calebporzio did was to ignore the APP_URL value if it's set to localhost to not interfere with people's local development habits. Which is great. But uses it in all other cases. I suppose the best option might be to open a PR that allows for an override of that behavior based on a configuration variable. 

The other option, since he actually uses $config('app.url') is to go into config/app.php and change the behavior there to check for a subdomain on your host and return the full host with subdomain if one exists.

**Comment by edgrosvenor** [comment]
@intellow I got config(['app.url' => $scheme.$host]) to work for me. You can either use that or edit the config/app.php file to return  scheme://host for url and you'll be all set.

**Comment by ceejayoz** [comment]
@edgrosvenor Just be aware that doing it in the config file will interact in nasty ways with Laravel's config caching.

**Comment by edgrosvenor** [comment]
@ceejayoz Good point. Yes, it's probably best to do the config(['app.url' => $scheme . '://' . $host]) in either the Livewire component itself or the controller of the page in which the component is embedded.

**Comment by intellow** [comment]
I'm working on a PR that would allow you to pass your base url into the `@livewireAssets()` blade directive. I think this is a pretty elegant solution to this problem.

**Comment by intellow** [comment]
PR #170 has been submitted

**Comment by intellow** [comment]
Dev-master is now working. No need to pass in anything to `@livewireAssets`. Thanks @calebporzio! Should be working for everyone else on the next release.

**Comment by calebporzio** [comment]
Thank YOU
