### ISSUE TITLE
Dynamic HTML classes

### ISSUE THREAD

**Issue by jrseliga** [calebporzio/livewire#161]
**Is your feature request related to a problem? Please describe.**

This always feels a little grim, especially with even longer class lists
```blade
<div class="{{ $active ? 'bg-green' : '' }} a whole mess of additional utility classes are here">
    {{-- stuff --}}
</div>    
```

**Describe the solution you'd like**

Would be interesting to have built-in support for dynamic HTML classes using truthy tests similar to Vue.

Something like this might be the easiest to implement:

```blade
<div
    wire:class="@json(['bg-green' => $active])"
    class="a whole mess of additional utility classes are here"
>
    {{-- stuff --}}
</div>
```

Though this feels a bit better:

```blade
<div
    wire:class="{{ ['bg-green' => $active] }}"
    class="a whole mess of additional utility classes are here"
>
    {{-- stuff --}}
</div>
```

**Comment by calebporzio** [comment]
I agree the ternary with empty string is a pain.

I would suggest creating a custom blade directive to handle this.

Something like: `@class($active, 'is-active')`

Not sure, but don't think this behavior would be better left to Blade than Livewire.

Closing for now.
