### ISSUE TITLE
Session never expires

### ISSUE THREAD

**Issue by larryx64** [calebporzio/livewire#171]
**Is your feature request related to a problem? Please describe.**
The user session never expires.

**Describe the solution you'd like**
I'm guessing this is to avoid errors if the component has to refresh and the session expired. But what if we need the session to expire after the time set in config/session.php?

**Describe alternatives you've considered**
We could extend the StartSession middleware so that whenever the header X-Livewire-Keep-Alive is present in the request, we optionally don't extend the cookie lifetime, we just leave the expiration date as is.

**Comment by calebporzio** [comment]
Ooooh, I like that.

Good catch, I think you're right on this.

Do you feel able to PR?

**Comment by larryx64** [comment]
I've tinkered a little on this solution. I think I might be able to PR this next week.

**Comment by calebporzio** [comment]
Great, looking forward to it!

**Comment by larryx64** [comment]
I've been thinking about this, and instead of trying to set the cookie expiration date as is (which I've been having a hard time doing. Getting the initial expiration date of the cookie is harder than I thought it would be), wouldn't it make more sense to maybe use a `.env` variable (maybe something like LIVEWIRE_KEEP_ALIVE?) and just *not* send the keep-alive request in our JS file?

**Comment by larryx64** [comment]
Hi Caleb.

Have you given the second proposition any thoughts? I think not making the keep-alive call would make more sens, since we would not be doing anything on the backend.

But by playing a bit with the package, I've come to realise a `.env` variable would not work since it is pre-compiled in the package.

I've noticed the `@livewireAssets` blade directive takes an array of options as a parameter.
So what about something like `@livewireAssets(['keep-alive' => false])` ?

**Comment by calebporzio** [comment]
Yeah, good question. I think you're right. `keep-alive` is just a bad idea? Maybe we just kill it for now?

I added it because getting page expired messages is such a pain, but it's there for a reason. Better to just extend the `SESSION_LIFETIME` of the app to ease that pain.
