### ISSUE TITLE
Variable is not being passed to view

### ISSUE THREAD

**Issue by oliverbj** [calebporzio/livewire#178]
**Describe the bug**
I have below component called `CreateForm`:

```php
public $stream;

public function mount(Stream $stream)
{
    $this->$stream = $stream;
}

public function render()
{
    return view('livewire.streams.fields.create-form');
}
```

In my blade view, I pass the `$stream` variable, like: 

```html
@livewire('streams.fields.create-form', $stream)
```

And then finally, in my LiveWire blade component, I try to access it:

```html
<div>
   {{dd($stream)}}
</div>
```

However, above returns `null`. If I die and dump the `$stream` variable inside the LiveWire component class (CreateForm.php), it is *not* null.

**Expected behavior**
The expected behavior is that the `$stream` variable is available within the LiveWire blade component.

**Comment by buismaarten** [comment]
Change `$this->$stream = $stream;` to `$this->stream = $stream;`.

Note the dollar sign after `$this->`.

**Comment by oliverbj** [comment]
Ah, no idea why my IDE (or me, lol!) didn't catch that! Thanks.

Now I receive an `CannotAddEloquentModelsAsPublicPropertyException` and can see that this is being worked on in #27.

Thanks @buismaarten!

**Comment by buismaarten** [comment]
According to [https://livewire-framework.com/docs/component-basics/](https://livewire-framework.com/docs/component-basics/).

It says: `You may want to set an Eloquent model(s) as a public property. This is illegal in Livewire for securty reasons.`

**Comment by 2kodes** [comment]
@oliverbj @buismaarten 
however caleb [also noted possible workarounds ](https://github.com/calebporzio/livewire/issues/27#issuecomment-521040661)
