### ISSUE TITLE
string to be encoded contains characters outside of Latin1 range

### ISSUE THREAD

**Issue by erikscheepers** [calebporzio/livewire#182]
I get this error when polling a result (containing characters like ♫ and ♪) from my database:

> Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range

I could fix the issue for me by replacing "_btoa(string)_" by "_btoa(unescape(encodeURIComponent(string)))_" using [this google-result](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte)

Unfortunately I couldn't reproduce this error in a simple environment:
```php
namespace App\Http\Livewire;
use Livewire\Component;
class Counter extends Component
{
    public $string;

    public function mount()
    {
        $this->string = '♪&nbsp;♫&nbsp;♫';
    }

    public function hydrate()
    {
        $this->string = '♪&nbsp;♫&nbsp;♫';
    }

    public function render()
    {
        return view('livewire.counter');
    }
}
```
```html
<div wire:poll="$refresh">
    {!! $string !!}
</div>
```
Maybe somebody else has more luck, or my fix helps others experiencing the same error.

**Comment by calebporzio** [comment]
I'd love a PR for that fix if it works for you

**Comment by erikscheepers** [comment]
Issue is fixed
