### ISSUE TITLE
Not Working if namespace is not App

### ISSUE THREAD

**Issue by jetwes** [calebporzio/livewire#192]
**Describe the bug**
Unable to find component

**To Reproduce**
My laravel App is named "Portal" instead of "App" - the component discovering won't work

**Expected behavior**
Show Livewire Component

**Additional context**
namespace App is hardcoded in LivewireMakeCommandParser.php@classNamespace and Component.php@getName

Solution: change it to config('app.name') instead of 'App'

**Comment by buismaarten** [comment]
`config('app.name')` won't be a solution because this should be the name of the application, not `App`.

**Comment by jetwes** [comment]
You are right. There should be a dedicated config file where the default namesoace is defined.

**Comment by christoffertyrefors** [comment]
Illuminate\Contracts\Foundation\Application::getNamespace() will return the correct namespace. Livewire are not including anything but illuminate/support and illuminate/validation at this stage, but I doubt that it's supposed to work outside of a laravel instance anyway?
