### ISSUE TITLE
CannotAddEloquentModelsAsPublicPropertyException issue

### ISSUE THREAD

**Issue by ryandylan** [calebporzio/livewire#198]
Hello,

i try to pass a value from the datasbase in the mount function

what i do:

```
	public function mount($id)
	{
		$this->id = $id;
		$this->urls = Project::find($this->id)->blacklists;
	}
```

And then i just try to access it in my view, but i get the following error: "CannotAddEloquentModelsAsPublicPropertyException"

Thanks in advance and sorry if there is already an open issue about it, my internet is not working correctly right now

**Comment by 2kodes** [comment]
hello @ryandylan for now the best option is to set the value for the Eloquent models in the render() function..

You can [find other solutions to this here](https://github.com/calebporzio/livewire/issues/27#issuecomment-521040661)

**Comment by intrepidws** [comment]
@ryandylan A solution for this has been released here: https://github.com/calebporzio/livewire/releases/tag/v0.3.0

**Comment by calebporzio** [comment]
Thanks for the guidance @intrepidws and @2kodes, closing this.
