### ISSUE TITLE
Make the stub component a little more strict

### ISSUE THREAD

**Issue by NoxxieNl** [calebporzio/livewire#207]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
In the `component.stub` no docblock or return value statement is used for generating a new livewire component.

**Describe alternatives you've considered**
Add docblocks and return types :-)

**Additional context**
I am happy to make a PR for this, though first trying to see if it would be merged anyway :-).

**Comment by calebporzio** [comment]
Hey @NoxxieNl, thanks for being willing to contribute (and actually doing it).

I personally am not a fan of return types OR docblocks. I like the boilerplate to be as minimal as possible. 

Perhaps in the future we will allow users to customize their own stubs for the Livewire make command.

**Comment by NoxxieNl** [comment]
I think i can make that :-). Will send a PR in a couple of days to make your own stub when you want.
