### ISSUE TITLE
Debugbar conflict

### ISSUE THREAD

**Issue by tillkruss** [calebporzio/livewire#217]
When enabling the Laravel Debugbar livewire doesn't work.

```
livewire.js?id=5445dbc922176760c0d5:2123 Uncaught (in promise) TypeError: Cannot read property 'storeResponse' of null
    at Component.receiveMessage (livewire.js?id=5445dbc922176760c0d5:2123)
    at Connection.onMessage (livewire.js?id=5445dbc922176760c0d5:3054)
    at Object.Connection.driver.onMessage (livewire.js?id=5445dbc922176760c0d5:3030)
    at livewire.js?id=5445dbc922176760c0d5:2901
```

Fixing this would help quite a bit in debugging the XHR requests.

**Comment by billriess** [comment]
Curious which debug bar are you using? The older one that has been around for a while or the newer Telescope based one?

**Comment by tillkruss** [comment]
Telescope works fine, it’s the old “laravel debug bar”.

**Comment by edgrosvenor** [comment]
Are both packages up to date? I’m not having any trouble with the combination.

**Comment by billriess** [comment]
@tillkruss try using the telescope debug bar. It is by the same person but uses telescope on the backend instead of duplicating the logic.

https://github.com/fruitcake/laravel-telescope-toolbar

**Comment by tillkruss** [comment]
Yes, both packages are up-to-date.

@calebporzio: I updated the error above with the un-minified assets.

<img width="493" alt="Screen Shot 2019-09-04 at 1 35 44 PM" src="https://user-images.githubusercontent.com/665029/64289423-fd755280-cf18-11e9-9b6e-f7241083a1d4.png">

**Comment by tillkruss** [comment]
@billriess: The Telescope toolbar works fine! 👌🏻

**Comment by calebporzio** [comment]
Installed classic debugbar, and everything works fine. Hmm, any ideas? 

![image](https://user-images.githubusercontent.com/3670578/64477546-e2018600-d16a-11e9-9de9-553f439263b9.png)

**Comment by tillkruss** [comment]
Maybe it was my custom config? I ended up switching to the Telescope Toolbar.

**Comment by chrypro** [comment]
I am actually having the same problem with both debugbar and telescope toolbars.

None of them is showing up on pages that use Livewire. (any other routes are showing the toolbars fine) 

The page is using Route::livewire() method but other than that the page is really simple. (I am just testing livewire at this point) 

Will keep debugging.

**Comment by chrypro** [comment]
After some debugging I found the problem to be here: https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/RouteCollector.php#L61

In the case of a livewire page the value of `$action['controller']` is a closure.

Adding an additional check `is_string($action['controller'])`  in the if statement "solves" the problem and the debugbar shows up

**Comment by calebporzio** [comment]
@chrypro - is this something you could PR to the project?
