### ISSUE TITLE
Make livewire.js non-blocking 

### ISSUE THREAD

**Issue by tillkruss** [calebporzio/livewire#224]
Is there a reason why the script is not using the `async` or `defer` attribute?

Can we make it `async` by default? Happy to submit a PR.

**Comment by calebporzio** [comment]
Yeah, good question. I can't think of a reason why not to. The Livewire initialization stuff is under a "DOMContentLoaded" listener. So we would just have to make sure that the Livewire assets are loaded before we try to initialize them. Would "defer" potentially make the assetse load after the "DOM ContentLoaded" listeners are run?

**Comment by sebastiandedeyne** [comment]
I was thinking the same!

I'd then recommend registering `@livewireAssets` in the `head` tag instead of at the end of the page. This would have the added bonus that the `loading` and `dirty` selectors will be available sooner (this could make a difference on very large pages)

**Comment by tillkruss** [comment]
@calebporzio: Do you want a PR, or tackle this yourself?

**Comment by calebporzio** [comment]
A PR would be great.

**Comment by tillkruss** [comment]
Closed with #222.
