### ISSUE TITLE
Root element doesn’t re-render

### ISSUE THREAD

**Issue by tillkruss** [calebporzio/livewire#245]
My root elements class attribute does not re-render when the $unseen property changes. It shows up as dirty, but the class list won’t change. 

![4530A9D2-5A6F-4CF7-B597-0D49E6835EB7](https://user-images.githubusercontent.com/665029/64476831-92aa5e00-d148-11e9-9156-64bf416d5e8a.jpeg)

**Comment by calebporzio** [comment]
Good catch, is fixed on master.
