### ISSUE TITLE
Delete is Extremely Slow

### ISSUE THREAD

**Issue by intellow** [calebporzio/livewire#256]
I have built what is basically a simple ToDo except it is adding and removing emails. When I add an email, it takes about 100ms which is fast enough for me. However, the delete is taking close to 600ms. It's shocking that it takes this long considering all that function is doing is executing one line of code: `Model::find($id)->delete();`

I have other Livewire implementations where the same type of functionality is not nearly as slow. I'm just wondering where to start with debugging this. Is it possible there's some kind of cache that needs to be cleared or something? I'm running version 0.3.2 if that matters.

![slowdelete](https://user-images.githubusercontent.com/40676515/64620801-2af34d80-d3aa-11e9-8f3d-82d0f270beda.gif)

My component and blade:

```
<div class="form-row">
    <h4 style="width: 100%;">Email CC for Participants</h4>
    <h6 style="width: 100%">If a participant is not connected to any housing locator or case manager, cc the following emails.</h6>
    <!-- Email Form Input -->
    <div class="form-group label-floating bmd-form-group col-md-6" wire:ignore>
        <label for="email" class="bmd-label-floating">Add Email (Press Enter)</label>
        <input type="text" name="email" class="form-control" wire:model="email" wire:keydown.enter="addEmail"/>
        @if($errors->has('email'))<div class="input-error">{{$errors->first('email')}}</div>@endif
    </div>
    <div class="col-md-6" style="display: flex; justify-content: center; align-items: center; flex-wrap: wrap;">
        @foreach($emails as $email)
            <div class="badge badge-info" style="font-size: 14px; margin: 5px 5px 0;">{{$email->email}}<span><i class="material-icons" style="font-size: inherit; cursor: pointer; margin-left: 10px;" wire:click="deleteEmail('{{$email->id}}')" wire:ref="delete-button-{{$email->id}}">close</i></span></div>
            <div wire:loading wire:target="delete-button-{{$email->id}}" class="text-danger">
                Removing Email...
            </div>
        @endforeach
    </div>
</div>
```

```
class TenantCc extends Component
{
    public $email;

    public function render()
    {
        return view('livewire.tenant-cc', [
            'emails' => request()->user()->tenant->tenant_notification_emails,
        ]);
    }

    public function addEmail()
    {
        $this->validate([
           'email' => 'required|email',
        ]);

        request()->user()->tenant->tenant_notification_emails()->create([
            'email' => $this->email,
        ]);
    }

    public function deleteEmail($id)
    {
        TenantNotificationEmail::find($id)->delete();
    }
}
```

**Comment by tillkruss** [comment]
This seems unrelated to Livewire, no?

If your database query is too slow, try adding an index, or queuing the delete.

**Comment by tillkruss** [comment]
Try using Telescope or even Blackfire to see what's taking so long.

**Comment by intellow** [comment]
There are a few other DB calls I can see in telescope but the combined duration is still very short. I will have to figure out if there's a way for telescope to give me any more information.

![image](https://user-images.githubusercontent.com/40676515/64887660-baa92e00-d62e-11e9-9a49-d9206539c10c.png)

**Comment by tillkruss** [comment]
What does the Chrome timing tab say when you inspect the request?

**Comment by intellow** [comment]
I've narrowed it down to the following method by inserting dump(now()); before and after methods and looking at when there's a 400+ ms difference. I'm not exactly sure what's going on in this method so I will try to understand it better.

```
// HandlesActions.php
protected function resolveActionParameters($method, $params)
    {
        return collect((new \ReflectionMethod($this, $method))->getParameters())->map(function ($parameter) use (&$params) {
            return rescue(function () use ($parameter) {
                return app($parameter->getClass()->name);
            }, function () use (&$params) {
                return array_shift($params);
            }, false);
        });
    }
```

**Comment by intellow** [comment]
So I think I found the fix. Hopefully this can be reviewed and merged soon. 😄
