### ISSUE TITLE
Global / Prop State Store

### ISSUE THREAD

**Issue by davidpiesse** [calebporzio/livewire#26]
I have several components with each needing some access to one or another's data. In Vue you might use vue-x to store some global props that all could get and set. Currently I have to repeat myself in each component that needs the data.

I am thinking along the lines of the ability to add a trait to a LivewireComponent that provides access to some global store of data. This could then be accessed inside a component
```php
public function mount()
{
    // Get a value from the store
    $current_page = $this->store->getCurrentPage();
    // Set a store value
    $this->store->setCurrentPage(420);
}
``` 
This could also fire off events to the event bus such as
```php
$this->store->setCurrentPage(420);
// fires off 
$this->emit('current-page.updated')
```

--
To define a store there would need to be a class that implements the Store interface and is registered in a provider before any components
```php
use Livewire\Store;

class LwStore implements Store {}
```
AppServiceProvider.php
```php
public function boot()
{
    Livewire::store(LwStore::class);
    Livewire::component(TodoList::class);
}
```
A Store would be a stripped down class that has props, events and get / set methods. They can be overridden in PHP for custom functionality.

The Store/States data would be store in the PHP session so it is persisted and not needing to be constantly sent back and forth to the front end JS.

The alternative to this would usually be wrap everything in one big component - but that seems a worse option than using any components.  

Also I know Store is an already used name internally so maybe State is better?

Happy to try and hack at it if you think its a good idea :)

**Comment by calebporzio** [comment]
Closing this for now.

**Comment by davidpiesse** [comment]
@calebporzio Does this count as the ignition for Cache 😃 ?!
Is the cache just per component or is there a global-ness to it as well?

**Comment by calebporzio** [comment]
@davidpiesse - the cache is per-component. A global cache would be interesting too, we'd just have to see some good use cases for it, and managing the garbage collection would be whacky.

So, the ignition? Sure!

**Comment by davidpiesse** [comment]
Whacky indeed! :)

**Comment by besrabasant** [comment]
@davidpiesse Any progress on this issue :)

**Comment by Saltibarsciai** [comment]
It's 2021, maybe there's some news on state (store) alternative like vuex? :) I really like laravel, but web I'm working needs to  be interactive as hell. I'd like to have SSR so I'm looking into livewire. but now I need to use js framework and store to keep code scalable, Drawback is that on initial load I got blank screen till js bundle parses.

**Comment by torian257x** [comment]
there should be some solution for global store. Vuex and redux are bad frameworks for state store (in my opinion). Too complex for simple functionality.

But vue3 fixed that issue by introducing a wayyy simpler state store https://v3.vuejs.org/guide/state-management.html#simple-state-management-from-scratch that is actually useful

react has zustand as library (far superior to context)
https://github.com/pmndrs/zustand

livewire has nothing? it's a bit a show stopper imho. A "pull the plug" reason for me. State handling and problems are absolutely awful, a waste of time.  That is btw the main reason for me to use livewire in the first place. Easier.

is there maybe a working workaround? obviously optimally I don't want to manually trigger updates

**Comment by keizah7** [comment]
Any updates?
