### ISSUE TITLE
Setup CI linting

### ISSUE THREAD

**Issue by fgilio** [calebporzio/livewire#43]
Just as a reminder.

**Describe the solution you'd like**
Something like StyleCI or similar. So there's no fuss around code formatting once the repo is public.

**Comment by calebporzio** [comment]
Sorry, by "Laravel Codebase" I meant: vendor/laravel/framework, not just a new laravel project. Make sense? I wonder if it would still pass from that folder?

**Comment by wotta** [comment]
I will check out if the linter passes on de vendor/laravel folder. I will let you know what the results are.

**Comment by calebporzio** [comment]
StyleCI and Travis are now implemented

**Comment by fgilio** [comment]
Niice!
