### ISSUE TITLE
wire:loading not removed in case of request error

### ISSUE THREAD

**Issue by lucasromanojf** [calebporzio/livewire#54]
**Describe the bug**
When a backend error happens, wire:loading is not reverted from the element.

**To Reproduce**
1. Implement the counter example
2. Put a wire:loading.attr="disabled" on each + and - button
3. Throw an exception from increment (or decrement) function
4. Click the button that throws the exception
5. An exception popup will be shown and, after closing it, the buttons will remain disabled, and the user will need reload the page

**Expected behavior**
It's expected that wire:loading is reverted not only after request success, but after request errors too

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3 MATE 64 bits
 - Browser: Chrome 75.0.3770.100 (64 bits)

**Comment by davidpiesse** [comment]
Would the blank space (T-Swizzle yah!) in component/index.js 
```js 
unsetLoading(loadingEls) { 
// No need to "unset" loading because the dom-diffing will automatically reverse any changes.
}
```
be a good place for this?
It's called on receiveMessage currently - but if we add/ move it to 
```js
messageSendFailed() {
        this.unsetLoading(this.messageInTransit.loadingEls)
        this.messageInTransit = null
    }
```

**I have written to the code to do this**  🎊 : - BUT I can't work out how to throw a PHP error from a called action in Jest.... Do I just mock a 500 response?

D

**Comment by calebporzio** [comment]
@davidpiesse - awesome, thanks for taking point on this - yeah, you would have to do something like that
