### ISSUE TITLE
v3 Released in Packagist

### ISSUE THREAD

**Issue by nathanheffley** [calebporzio/livewire#57]
**Describe the bug**
v3 was tagged back in May, even though the newest version is (currently) v0.1. Composer/Packagist now download this old version by default if you follow the steps in the documentation.

**To Reproduce**
1. Install the package using Composer

**Expected behavior**
I expected to download the most recently released version.

**Comment by google-mac** [comment]
This is what I just ran into as well!

**Comment by nathanheffley** [comment]
The current fix for this is to just update your `composer.json` to have the correct version specified (`^0.1`) but I think the incorrect version should be removed from Packagist at least so it stops downloading/updating, and probably untagged in git so it doesn't cause any confusion when v3 actually gets released.

**Comment by nathanheffley** [comment]
Looks like @calebporzio fixed this in response to #58 👍
