### ISSUE TITLE
@livewireAssets not injecting

### ISSUE THREAD

**Issue by google-mac** [calebporzio/livewire#58]
When I visit the resulting HTML, it is rendered as `@livewireAssets`. I checked the source that is current from Composer and it does not include this as a blade directive. Only the `livewire()` directive is available.

1. Create a new Laravel app
2. Install Livewire
3. Follow the quickstart from the docs
4. JS not injected

**Comment by google-mac** [comment]
The cause is outlined in https://github.com/calebporzio/livewire/issues/57.

**Comment by nathanheffley** [comment]
Since this is just a version issue you should probably close this issue so as not to cause any unnecessary confusion.

**Comment by calebporzio** [comment]
Shoot, should be good now

**Comment by calebporzio** [comment]
close this if it works

**Comment by allmanaj** [comment]
I'm on v0.1 now and It still seems to be rendering as `@livewireAssets` at the bottom of my template

**Comment by nathanheffley** [comment]
v0.1 is working fine for me in a new project. Did you remove your vendor folder and lock file and try completely reinstalling your dependencies?

**Comment by google-mac** [comment]
@calebporzio @allmanaj I did not see the `@livewireAssets` injected UNTIL I re-saved the file where I was injecting it.

**Comment by alexpgates** [comment]
Using `{!! Livewire::assets() !!}` instead seems to work until the blade directive is fixed.

**Comment by google-mac** [comment]
@alexpgates The blade directive is working.

**Comment by stuartcusackie** [comment]
I'm seeing this problem. I just installed livewire today on my PC dev environment with the latest version of Laravel. It works fine on the production server and on my PC but when I move to my laptop dev environment I see @livewireAssets. I have run both composer update and npm run dev.

Using {!! Livewire::assets() !!}  fixes it so I think you still have bug in the blade directive.

**Comment by calebporzio** [comment]
@stuartcusackie - can you think of something Livewire could have done to make this experience better for you? What kind of error could it have thrown?

**Comment by stuartcusackie** [comment]
@calebporzio I'm afraid I can't remember what the exact line of code was, but I believe it was in my livewire controller. I had forgotten to run a migration on one of my development machines so a particular object property that livewire was looking for in it's mount() function did not exist. It took me a while to figure out because the only indication that something was wrong was seeing @livewireAssets when viewing the site.

Is it possible to flag such errors or is error reporting limited due to the nature of livewire's technology? I might be wrong but I think Laravel would indicate a problem like this.

**Comment by calebporzio** [comment]
It sounds like whatever environment you were on just didn't have Livewire installed yet - the directive wasn't registering with Blade and was just echoing out.

I'm not sure there's much Livewire can do here.

**Comment by stuartcusackie** [comment]
I'm sure I had run composer update on the environment but I'm not ruling it out. Anyway, I'll keep an eye out for similar issues and report back. Thanks.

**Comment by Polfo** [comment]
I use @liveWirestyles in version ^2.0
