### ISSUE TITLE
Testing Components can generate false positives from `wire:data`

### ISSUE THREAD

**Issue by pddevins** [calebporzio/livewire#62]
**Describe the bug**
Calling `assertSee` on `Livewire::test(Component::class)` can produce false positives when looking for text on the page that exists within the `json` payload in `wire:data`.

**To Reproduce**
1. Create a component `Post` through the artisan command
2. Set up the route `Route::livewire('/posts', 'posts')` that lists a set of Posts with a `title` and `body` (just some basic data). Do not set up the template to show any Posts.
3. Write a test that checks that the first Post in the list is present on the page by checking the title appears using `assertSee`.
4. The test will pass.

**Expected behavior**
The test should fail because the first `Post`'s title shouldn't be listed on the page.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome
 - Latest of both

**Additional Info**
I believe that because the models are being json encoded in `wire:data`, it ends up providing a false-positive when checking the DOM for text coming from the model.

**Comment by devcircus** [comment]
Is this more of an issue with the way laravel implements assertSee than an issue with livewire?

**Comment by pddevins** [comment]
I don't think it is, but I'm open to being convinced. It seems, as an end user (a developer writing tests) that the expectation should be : If I do not explicitly place text on the page, `assertSee` shouldn't see that text in the DOM. Do you see that as a reasonable expectation, or am I off base?

**Comment by devcircus** [comment]
Oh I definitely agree with the expectation. I just think that it may be because of how laravel checks for this. Anxious to get home and dig into it.

**Comment by calebporzio** [comment]
Yeah, I agree, ->assertSee from Livewire's API should behave better than that.

The problem is, how do we accomplish this. I wonder if we can just regex out the "wire:data" inside the "assertSee" method? because livewire generates wire:data, it would be pretty secure I think. I'll be traveling until the middle of next week so any help on this is welcomed.

**Comment by pddevins** [comment]
Yea. Nice! I'm back home today, so I'll look into it and see what I can do. 👍

**Comment by pddevins** [comment]
[PR](https://github.com/calebporzio/livewire/pull/74) is in. Open to suggestions and requests 👍
