### ISSUE TITLE
Wrong imports in some package files

### ISSUE THREAD

**Issue by mateusjunges** [calebporzio/livewire#63]
When running `npm run watch`, my terminal show 3 compilation errors:
```
These relative modules were not found:

* ../store in ./src/js/connection/index.js
* ./component in ./src/js/index.js
* ./store in ./src/js/index.js    
```
Is is correct?
When i change it to `../Store`, `./Component` and fix other directories with the same typo, the errors disappear.

Can i send a PR fixing it and also adding some alias for js files?

**Comment by calebporzio** [comment]
please do
