### ISSUE TITLE
Cannot Complete Action on Route with Middleware

### ISSUE THREAD

**Issue by intellow** [calebporzio/livewire#64]
I created the counter component and it's working fine on most pages, but it doesn't work on a page with the following middleware:

`Route::get('/properties/{property_id}/edit/floorplans', [FloorplanController::class, 'showSetFloorplans'])->middleware('canManageProperty');`

And the canManageProperty middleware is:
```
$property = Property::findorfail($request->route('property_id'));
if ($request->user()->canManageProperty($property)) {
    return $next($request);
} else {
    abort(403);
}
```

When I try to use the counter component (or any livewire click action, I just tested on the quickstart component to make sure it wasn't any problem with my code), I get a popup modal with a 404. For some reason it's hitting that middleware, not finding a "property_id" on the route, and the findorfail is failing.

If I remove this middleware the component works.

**Comment by calebporzio** [comment]
Yeah, so right now, every livewire request inherits the middleware of the request that the page loaded with.

This is a security measure I thought would be good, but I'm open to talking through it.

**Comment by calebporzio** [comment]
Here's a new feature that should allow you to exclude middleware conditionally for Livewire:

https://livewire-framework.com/docs/security/
