### ISSUE TITLE
Allow "wire:ref" to be assigned to multiple targets

### ISSUE THREAD

**Issue by intrepidws** [calebporzio/livewire#65]
**Is your feature request related to a problem? Please describe.**
I have a page with many buttons, several of which (but not all of which) I would like to have trigger the same loading state. It appears that the relationship between `wire:target` and `wire:ref` is 1 to 1 and doesn't allow 1 to many.

**Describe the solution you'd like**
Perhaps just allowing a `wire:ref` to be assigned to multiple things at the same time?

**Describe alternatives you've considered**
As of now, at least as far as I can tell, the only solution is to create a specific loading state for each button.

**Additional context**
It might also be nice to allow a loading state to have multiple targets specified for `wire:target`.

**Comment by calebporzio** [comment]
Ok @intrepidws, after thinking about the various options. Here's what I think is best:

```html
<button wire:ref="foo">
<button wire:ref="bar">

<div wire:loading wire:target="foo, bar">...</div>
```

I implemented this in the master branch. It will be available with the next release.

**Comment by intrepidws** [comment]
Cool, thanks @calebporzio
