### ISSUE TITLE
v3 tag makes composer pull wrong version

### ISSUE THREAD

**Issue by luisdalmolin** [calebporzio/livewire#66]
**Describe the bug**
There's a `v3` that's making `composer require calebporzio/livewire` gets the wrong version.

**To Reproduce**
Run `composer require calebporzio/livewire` on a new project.

**Expected behavior**
Get the `0.1` version. I guess the `v3` tag should be deleted.

**Screenshots**
![](https://www.dropbox.com/s/bfcp1x8oyx27t6y/Screenshot%202019-07-26%2010.50.55.png?raw=1)

**Comment by intrepidws** [comment]
I had the same problem. Until this is fixed, you can use this in your composer.json:

`"calebporzio/livewire": "^0.1",`

**Comment by calebporzio** [comment]
Shoot, I did that yesterday, not sure how it got back in there. Should be good again
