### ISSUE TITLE
Livewire breaks with import Vue from 'vue'

### ISSUE THREAD

**Issue by luisdalmolin** [calebporzio/livewire#67]
**Describe the bug**
Apparently, Livewire breaks when I use `import Vue from 'vue'` instead of `window.Vue = require('vue')`. I took me a while to figure out, so I pushed a repo with the code that is failing.

app.js: https://github.com/luisdalmolin/livewire-bug-report/blob/master/resources/js/app.js
main view: https://github.com/luisdalmolin/livewire-bug-report/blob/master/resources/views/welcome.blade.php
livewire component class: https://github.com/luisdalmolin/livewire-bug-report/blob/master/app/Http/Livewire/ComponentCreate.php
livewire component view: https://github.com/luisdalmolin/livewire-bug-report/blob/master/resources/views/livewire/component-create.blade.php

I can try to figure this out next week if not solve until there.

**To Reproduce**
1. Clone this repo https://github.com/luisdalmolin/livewire-bug-report
2. `composer install && yarn install && yarn run dev`
3. Open in browser
4. Type anything on any of the fields and you will get the `Uncaught (in promise) TypeError: Cannot read property 'getAttributeNames' of null` error on console

**Expected behavior**
Not throw the `Uncaught (in promise) TypeError: Cannot read property 'getAttributeNames' of null` error.

**Screenshots**
![](http://g.recordit.co/Zw0pWXICBO.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by calebporzio** [comment]
This makes sense - Livewire won't work with Vue unless it can detect it in the browser somehow. 

I believe this should just be a requirement for using Vue with Livewire.

Maybe we should add a note to the docs:

> In order to use Livewire with Vue. A `window.Vue` object must be made available to Livewire.

**Comment by calebporzio** [comment]
Re-open if I've missed something.

**Comment by luisdalmolin** [comment]
Yeah makes sense, a note to the docs should be enough
