### ISSUE TITLE
Inputs lose focus if DOM **before** input is removed when Livewire updates

### ISSUE THREAD

**Issue by owenconti** [calebporzio/livewire#75]
**Describe the bug**
When DOM nodes **before** an input are removed due to a Livewire update, the input your are typing in loses focus.

Here's a GIF showing the DOM change, but not be removed (the alert box), this works fine:

![livewire-error-2 2019-07-26 21_05_05](https://user-images.githubusercontent.com/791222/61989227-5cc27780-afe9-11e9-8c26-72ea7a9ef75b.gif)

Here's a GIF showing the DOM **after** the input be removed, this works fine:

![livewire-error-3 2019-07-26 21_05_39](https://user-images.githubusercontent.com/791222/61989228-6cda5700-afe9-11e9-8cee-38784cb46ba5.gif)

Here's a GIF showing the DOM **before** the input be removed, this causes the focus in the input to be lost:

![livewire-error-1 2019-07-26 21_05_25](https://user-images.githubusercontent.com/791222/61989233-7c59a000-afe9-11e9-8b1e-95c64006d719.gif)

**Expected behavior**
Input is able to keep focus while DOM around it is removed/modified.

**Desktop (please complete the following information):**
OS: Mac OS
Browser: Brave

**Comment by davidpiesse** [comment]
Hi @owenconti  
Do you know what the offending code that does this is?
It could be a morph Dom issue or a way Livewire handles inputs ... Any ideas on which it might be?
Ps. Thanks for the GIFs. 👍

**Comment by owenconti** [comment]
@davidpiesse I am not sure.

I can understand why it happens though. I'm inserting new DOM that the Livewire JS hasn't seen before which I could understand throws off it's ability to track the `<input />`.

FWIW, I did try using `wire:key` on the elements, but that didn't seem to help either. Seems like Livewire gets confused if the DOM structure changes on an update, even when using `wire:key`.

**Comment by calebporzio** [comment]
@owenconti - I'd like to investigate - but please post a sample template code that I can just copy and paste to replicate the issue locally. Thanks.

**Comment by owenconti** [comment]
@calebporzio Yep, here you go:

Template code:

```
<div class="panel">
    <form wire:submit.prevent="createContact">
        @if ($errors->isNotEmpty())
            <div class="alert alert-error">
                @foreach($errors->all() as $error)
                    <p>{{ $error }}</p>
                @endforeach
            </div>
        @endif

        <div class="form-group {{ $errors->has('name') ? 'error' : null  }}">
            <label class="form-label" for="name">Contact Name</label>
            <input type="text" class="form-input" wire:model="name" id="name" placeholder="Contact name" />
        </div>

        <div class="form-group flex justify-between">
            <button type="submit" class="btn">Save Contact</button>
            <a href="{{ url()->previous() }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
```

Component:

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class CreateContact extends Component
{
    public $name;

    public function updated()
    {
        $this->validateForm();
    }

    public function validateForm()
    {
        $this->validate([
            'name'    => 'required',
        ], [
            'name.required' => 'The Contact Name field is required.'
        ]);
    }

    public function createContact()
    {
        $this->validateForm();
    }

    public function render()
    {
        return view('livewire.create-contact');
    }
}
```

**Comment by calebporzio** [comment]
Hey @owenconti, I was able to reproduce the issue you're describing.

Here is the fix:

You need to wrap conditionally loaded DOM inside a tag. For example:

## Broken
```html
<form wire:submit.prevent="createContact">
        @if ($errors->isNotEmpty())
            <div class="alert alert-error">
                @foreach($errors->all() as $error)
                    <p>{{ $error }}</p>
                @endforeach
            </div>
        @endif
```

## Fixed
```html
<form wire:submit.prevent="createContact">
        <div>
            @if ($errors->isNotEmpty())
                <div class="alert alert-error">
                    @foreach($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach
                </div>
            @endif
        </div>
```

It's a problem with morphdom, the package Livewire uses to do the DOM diffing and patching. It's not intelligent enough to know that just one tag has been added and that the whole DOM hasn't been completely changed. It's frustrating and would love for someone to dive deep and come up with a solution that we could potentially PR to morphdom.

Hope this helps!

**Comment by owenconti** [comment]
@calebporzio Thanks for diving in and finding the root cause. Unfortunate about morphdom, but at least it's an easy work around.

Thanks

**Comment by calebporzio** [comment]
Yeah, no problem!

**Comment by jamesautodude** [comment]
> Hey @owenconti, I was able to reproduce the issue you're describing.
> 
> Here is the fix:
> 
> You need to wrap conditionally loaded DOM inside a tag. For example:
> 
> ## Broken
> ```
> <form wire:submit.prevent="createContact">
>         @if ($errors->isNotEmpty())
>             <div class="alert alert-error">
>                 @foreach($errors->all() as $error)
>                     <p>{{ $error }}</p>
>                 @endforeach
>             </div>
>         @endif
> ```
> 
> ## Fixed
> ```
> <form wire:submit.prevent="createContact">
>         <div>
>             @if ($errors->isNotEmpty())
>                 <div class="alert alert-error">
>                     @foreach($errors->all() as $error)
>                         <p>{{ $error }}</p>
>                     @endforeach
>                 </div>
>             @endif
>         </div>
> ```
> 
> It's a problem with morphdom, the package Livewire uses to do the DOM diffing and patching. It's not intelligent enough to know that just one tag has been added and that the whole DOM hasn't been completely changed. It's frustrating and would love for someone to dive deep and come up with a solution that we could potentially PR to morphdom.
> 
> Hope this helps!

I tried this but unfortunately it didn't help :/

It's weird because some don't do this, some do.

**Comment by AmodD** [comment]
just make sure the input field is not within a form or table tag
