### ISSUE TITLE
Data types in component state change after component is re-rendered.

### ISSUE THREAD

**Issue by DylanBaine** [calebporzio/livewire#77]
**Describe the bug**
An array of objects in the component state changes to an array of keyed arrays when the DOM is re-rendered.

**To Reproduce**
1. Create a component that has a property that holds and array of objects.
2. Add an input to the component that will add an object to that array.
3. Cause a re-render of the component and notice the object in the array is now a keyed array.

**Expected behavior**
Data types stored in the state of a component should stay the same data type.

**Screenshots**
<img width="991" alt="Screen Shot 2019-07-27 at 2 14 48 PM" src="https://user-images.githubusercontent.com/22332170/61998736-300a7080-b07a-11e9-9ce0-e6fefb979c1c.png">
<img width="864" alt="Screen Shot 2019-07-27 at 2 15 02 PM" src="https://user-images.githubusercontent.com/22332170/61998738-36005180-b07a-11e9-833b-4f10a02c6681.png">

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by davidpiesse** [comment]
Hi @DylanBaine Is this similar to #27 ?
D

**Comment by calebporzio** [comment]
This should be fixed in v0.2.5.

Values are not cast to primitives right away before reaching the view.

**Comment by doaaAbdelfatah** [comment]
is it solved I have the same problem please tell me how can I solve it

**Comment by michel-drewl** [comment]
what is the result in the hydration process when objects and collections are converted into arrays?
