### ISSUE TITLE
How to listen for document events like scroll?

### ISSUE THREAD

**Issue by miggiboy** [calebporzio/livewire#79]
Hi! Loving Livewire so far! Great job!

I wanted to build an infinite scroll component. So when I start scrolling I need to push more items to a list. How do I hook up to window events like scroll?

I tried a renderless vue component that fires scroll event. But livewire seems to not listen for custom events. And another concern is how do I stop firing ajax requests as soon as I reach the end of list?

**Comment by davidpiesse** [comment]
Hi! :)

I would do the scroll event in pure JS within a normal<script> tag.
https://livewire-framework.com/docs/custom-javascript/

Something like [this](https://codepen.io/wernight/details/YyvNoW) works for a ul.
Then from the JS use the event bus and it should work as below.
https://livewire-framework.com/docs/events/
```js
window.livewire.emit('update_list_action', any_vars)
```
I used this in the listener tests here so it 'should' work :D
https://github.com/calebporzio/livewire/blob/e90429cd75c19e9d088419c6c8640079057979b7/tests/js/event_listeners.spec.js

**Comment by miggiboy** [comment]
Hi @davidpiesse ! Thank you for helping me out. Emit method works. But I still have no idea on how to stop firing ajax requests I tried adding and removing listener conditionally like so:


<script>
        function loadMore () {
            window.livewire.emit('loadMore')
        };

        @unless ($complete)
            document.addEventListener('scroll', loadMore, true)
        @else
            document.removeEventListener('scroll', loadMore, true)
        @endunless
</script>

But as I understand rerendering js does't mean it will be triggered

**Comment by davidpiesse** [comment]
Hi @miggiboy 

How about this
```js
window.onscroll = function(ev) {
    if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
        window.livewire.emit('loadMore')
    }
};
```
I got this from here http://jsfiddle.net/8PkQN/1/ and it is only called ehn scrolling hits the bottom of the page.
It is better to have a single event driven by the scroll such as hitting 'rock bottom'

D

**Comment by miggiboy** [comment]
> Hi @miggiboy
> 
> How about this
> 
> ```js
> window.onscroll = function(ev) {
>     if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
>         window.livewire.emit('loadMore')
>     }
> };
> ```
> 
> I got this from here http://jsfiddle.net/8PkQN/1/ and it is only called ehn scrolling hits the bottom of the page.
> It is better to have a single event driven by the scroll such as hitting 'rock bottom'
> 
> D

Yeah, I like this solution. With this approach I don't have to think about removing event listener cause it seems to be no big deal anymore. Cool man! I appreciate your help

**Comment by davidpiesse** [comment]
No worries. 
👍
