### ISSUE TITLE
Does livewire support nested data binding?

### ISSUE THREAD

**Issue by miggiboy** [calebporzio/livewire#80]
What is syntax for nested data binding? Does it have to be a dot of array syntax?

**Comment by davidpiesse** [comment]
I may be wrong but I believe dot notation is the current approach.
It's not documented so if you do confirm this please do pr the docs repo 😁

D

**Comment by miggiboy** [comment]
Thanks! Dot notation worked! I'll make a pr, but first I need to learn how to make one)

**Comment by connecteev** [comment]
@miggiboy awesome. look forward to seeing the docs. You basically create a fork, commit changes to it and use github's UI to send in a PR: https://help.github.com/en/articles/creating-a-pull-request

**Comment by miggiboy** [comment]
@davidpiesse @connecteev 
Thanks you guys, made a PR just now. https://github.com/calebporzio/livewire-docs/pull/16

**Comment by davidpiesse** [comment]
Thanks for helping us out!
