### ISSUE TITLE
wire:fired="log" not working as expected

### ISSUE THREAD

**Issue by boxybird** [calebporzio/livewire#81]
**Describe the bug**
Wire listener not detecting event  `<div wire:fired="log"></div>`

**Expected behavior**
When clicking `<button wire:click="fired">Fire</button>` I would expect  `<div wire:fired="log"></div>` to call the `log()` method in the component class.

**Screenshots**
![class](https://user-images.githubusercontent.com/18317878/62012841-277c6d80-b140-11e9-84f8-8a7f080ad5cf.PNG)
![html](https://user-images.githubusercontent.com/18317878/62012842-277c6d80-b140-11e9-8bb4-a6939f953ca0.PNG)

**Desktop (please complete the following information):**
 - Browsers: Chrome and Firefox

**Comment by davidpiesse** [comment]
Hi @boxybird ,

I don't think that wire:fired is in the framework.
You are currently (I think) calling an action [fired] which in PHP land then emits an event [fired]. You then want another part of the component to respond to this and run an action [log].

You can emit events from the click handler itself if you wanted.
```js
<button wire:click="$emit('fired', 'nothing')"></button>
``` 
On the back end it is better to set up a listener property and then this could call the log method.
So Button emits event. Listener on Component is alerted to this and call the log() method.
https://livewire-framework.com/docs/events/

In your case this:
```php
protected $listeners = ['fired' => 'log'];
```   
David
Ps. If I missed the point let me know so I can answer correctly

**Comment by 2kodes** [comment]
@davidpiesse 

let me weigh in a bit

from checking the api reference at https://livewire-framework.com/docs/api/  there seems to be a line which states 

wire:foo="bar" | Listens for an event called "foo". (You can specify any event you would like to listen for this way)
-- | --

I think thats what @boxybird is trying to do

**Comment by davidpiesse** [comment]
Gotcha!
I can't get the same thing working either.
I can confirm that the event id getting fired in the 'fired' action and sent back in the response.

But I would expect that a listener is needing to be registered for ```wire:foo="bar" ``` to be available and listening...

@calebporzio have you got an idea where I can dig into this?

David

**Comment by calebporzio** [comment]
I think the confusion is caused by ambiguity in the docs. I fixed this. Here is the new copy:
![image](https://user-images.githubusercontent.com/3670578/62241932-22215c00-b3a8-11e9-8e2a-81fd83a5dfaf.png)

`wire:fired` will add a DOM event listener to the element, listening for "fired". It won't listen for a Livewire event (at least not right now, if there is a compelling use case, we can see about this).

You can listen to events in the back end with the `$listeners` property, and in the front-end, with the `livewire.on('fired'...` method.

**Comment by davidpiesse** [comment]
Would this be a good resource for DOM events?
https://developer.mozilla.org/en-US/docs/Web/Events

**Comment by calebporzio** [comment]
yes
