### ISSUE TITLE
dd() / dump() handler similar to the error popup window

### ISSUE THREAD

**Issue by allmanaj** [calebporzio/livewire#83]
I'm loving Livewire so far, and it's possible that I'm missing something, but while using it I've found it hard to debug issues and follow data flow around my app.

The Error popup which displays the normal Laravel error page as a modal is great, however, I think that something similar which works with `dump()` and `dd()` would be great to help with any issues I run into in development. 

I'm not totally sure how something like this could be implemented but I'm happy to look into creating a pull request if it's something which others would find useful

**Comment by cbaconnier** [comment]
I would definitely find this useful!

I didn't tested if it works (I don't see any reason it wouldn't) 
But you could `dump` with [beyondcode/laravel-dump-server]( https://github.com/beyondcode/laravel-dump-server)

**Comment by allmanaj** [comment]
I've got the code for this written and working just because I wanted to use it for my own little app and see if I could do it! I'll create a PR a little later 😄

**Comment by calebporzio** [comment]
Yeah, I generally use `dump()` with the dump server, but I admit it's not ideal. 

I'd love to see some code for this feature myself.

**Comment by calebporzio** [comment]
`dd()` will work in the latest release: v0.1.2

**Comment by kirkbushell** [comment]
I know this is super old, but was this removed? dd() doesn't appear to show the error popup like other exceptions in V3.

**Comment by kirkbushell** [comment]
lol nevermind, I simply misunderstood how I was meant to work with validation in livewire 🤦🏻
