### ISSUE TITLE
Jest testing broken - what have I done!?

### ISSUE THREAD

**Issue by davidpiesse** [calebporzio/livewire#94]
Getting almost all the Jest tests fail with the following error. 
```
TypeError: e.map(...).filter(...).flat is not a function
```

What have I done to my setup to bork it all up? (Have not changed anything except pull in the latest master)

**Comment by calebporzio** [comment]
Interesting... ".flat" IS indeed a function that Jest should understand. Did you update anything else?  I don't really know off the top of my head.

**Comment by davidpiesse** [comment]
That's what I thought!?

I will try a full npm rebuild. Nothing done since pre Laracon when it
worked; and it obv works for you...

D

**Comment by davidpiesse** [comment]
NPM Version was set to v10. Had to upgrade to v12 to get it working.
