### ISSUE TITLE
Add additional methods to Directives/Modifiers

### ISSUE THREAD

**Issue by davidpiesse** [calebporzio/livewire#99]
Add additional next() or after() to directive_manager.js and also modifiers for use elsewhere in the src code.

Just rifting right now as I may need to use the directives and feel like there could be a more focused way to interact with them.

For example having the stack as an [] and then being able to get the next() or after() or before(). This would be useful for something like ```wire:loading.delay.750ms```.
Ideally I could interact with this such as 
```js
//some if statements
directives.get(loading).get('delay').next()
//get the directive by name - then the get automatically looks for it's modifiers
//or
directives.get(loading).getModifier('delay').next()
```

Maybe also a directives.find that checks and returns (has & get together) like in Laravel.
 ```js
directives.find(loading).find('delay').next()
```

**Comment by davidpiesse** [comment]
For this wire:loading.delay I can use the durationOr to get the delay info and I guess its another if check for delay...
hmmmm.......

**Comment by calebporzio** [comment]
I think the current strategy is ok, yeah?
